### ISSUE TITLE
Update completes, but needs to update again

### ISSUE THREAD

**Issue by ardCOR3** [antrix1/arenamaster-addon#12]
Update completes, once logged into the game get Lua error. on checking curse-forge, the update is still available (same one). redone a few times same issue. Logged in and out. the game opens to Lua error. 
Do you need the Lua error for this?

**Comment by antrix1** [comment]
@hardCORE1234421 Can you share what Lua errors are popping up? As for the addon showing an update is still available, it happens to me as well, but from what I see the update was applied (data is fresh after updating once), even though it shows you can update again. That must be something with the Curse client.
