### ISSUE TITLE
Got an error when tooltip someone

### ISSUE THREAD

**Issue by qscgyjqscgyj** [antrix1/arenamaster-addon#14]
I getting 4 pages with errors reports in the game when I'm trying tooltip someone

**1 page report**
Message: constant table overflow
Time: Thu Nov 18 18:48:49 2021
Count: 1
Stack: constant table overflow
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\AddOns\ArenaMasterPvPInspect\core.lua"]:93: in main chunk

Locals: (*temporary) = "ArenaMaster_DB_EU"
(*temporary) = <function> defined =[C]:-1
(*temporary) = <table> {
 1 = 43
 2 = 54
 3 = 138
...

**2 page report**
Message: UNKNOWN ERROR
Time: Thu Nov 18 18:48:49 2021
Count: 1
Stack: UNKNOWN ERROR
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\AddOns\ArenaMasterPvPInspect\core.lua"]:93: in main chunk

Locals: (*temporary) = "ArenaMaster_DB_EU"

**3 page report**
Message: UNKNOWN ERROR
Time: Thu Nov 18 18:48:49 2021
Count: 1
Stack: UNKNOWN ERROR
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\AddOns\ArenaMasterPvPInspect\core.lua"]:93: in main chunk

Locals: (*temporary) = "ArenaMaster_DB_EU"

**4 page report**
Message: UNKNOWN ERROR
Time: Thu Nov 18 18:48:49 2021
Count: 1
Stack: UNKNOWN ERROR
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\AddOns\ArenaMasterPvPInspect\core.lua"]:93: in main chunk

Locals: (*temporary) = "ArenaMaster_DB_EU"

I tried to reinstall addon, delete it and install again but nothing helped me.
Thanks.

**Comment by antrix1** [comment]
@qscgyjqscgyj This is a work in progress. Should get the fix out today.

**Comment by qscgyjqscgyj** [comment]
> @qscgyjqscgyj This is a work in progress. Should get the fix out today.
