### ISSUE TITLE
Constant LUA Error

### ISSUE THREAD

**Issue by 1Botnet** [antrix1/arenamaster-addon#16]
Constant LUA Error:

https://i.imgur.com/2amQTwf.png

Reinstalled and I have the same issue.

**Comment by CreepyJoker** [comment]
Greetings. 
Thanks for the bug report. It would be helpful if you could post the entire error in text format here.

Meanwhile I will try to replicate it on my end and provide a fix for it.

Sorry for the late reply, I wasn't around for some time.

**Comment by BoomsiFTW** [comment]
Got as well a huge load of errors on just some players, when I do y mouseover.

Error Code:


`Message: ...e\AddOns\ArenaMasterPvPInspect\modules/framework.lua:192: bad argument #1 to 'gmatch' (string expected, got nil)
Time: Sun May  8 16:13:03 2022
Count: 284
Stack: ...e\AddOns\ArenaMasterPvPInspect\modules/framework.lua:192: bad argument #1 to 'gmatch' (string expected, got nil)
[string "=[C]"]: ?
[string "=[C]"]: in function `gmatch'
[string "@Interface\AddOns\ArenaMasterPvPInspect\modules/framework.lua"]:192: in function `AMPVP_ConvertStringToTable'
[string "@Interface\AddOns\ArenaMasterPvPInspect\modules/framework.lua"]:218: in function `AMPVP_ConvertRankAchievement'
[string "@Interface\AddOns\ArenaMasterPvPInspect\core.lua"]:421: in function `AMPVP_AddTooltipDetails'
[string "@Interface\AddOns\ArenaMasterPvPInspect\ui/ui.lua"]:368: in function <Interface\AddOns\ArenaMasterPvPInspect\ui/ui.lua:341>
[string "=[C]"]: ?`

**Comment by 1Botnet** [comment]
7344x ...eArenaMasterPvPInspect\modules/framework.lua:192: bad argument #1 to 'gmatch' (string expected, got nil)
[string "=[C]"]: in function `gmatch'
[string "@ArenaMasterPvPInspect\modules/framework.lua"]:192: in function `AMPVP_ConvertStringToTable'
[string "@ArenaMasterPvPInspect\modules/framework.lua"]:218: in function `AMPVP_ConvertRankAchievement'
[string "@ArenaMasterPvPInspect\core.lua"]:421: in function `AMPVP_AddTooltipDetails'
[string "@ArenaMasterPvPInspect\ui/ui.lua"]:318: in function <ArenaMasterPvPInspect\ui/ui.lua:297>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?

Locals:
(*temporary) = nil
(*temporary) = "[^ ]+"
(*temporary) = "string expected, got nil"

**Comment by CreepyJoker** [comment]
Cool, thanks for your reports. I will track down the issue tomorrow myself to see why that happens to some players only ( at a glance I see that they are missing some data from the titles achieved, so I have to look through the data & to properly test and mitigate that issue so it won't happen again ).

I will post here when the issue gets fixed.

Thank you for your time.

**Comment by CreepyJoker** [comment]
Done, thanks for your reports. I've tested the issue now and provided a fix for it. It should not happen again.

The fix will be live on the next data update ( probably today ).

If there's anything else popping up, let us know by creating another bug report.

Thank you for your reports and sorry for the delay.
