### ISSUE TITLE
Unable to Inspect and Copy from LFG

### ISSUE THREAD

**Issue by 1Botnet** [antrix1/arenamaster-addon#17]
When trying to inspect / copy a player from LFG it pulls their server correctly but just displays random numbers instead of their IGN.

**Comment by 1Botnet** [comment]
Still an issue.

No lua errors. Same issue with zero addons.

https://i.imgur.com/eUtZZXT.png

**Comment by CreepyJoker** [comment]
Cheers, thanks for your report. I will look into the issue and correct it, today I hope.

It seems that Blizzard made some API changes and it's not getting the info from the correct entry anymore.

Sorry for the late reply.

**Comment by 1Botnet** [comment]
Any update?

WIM and many others addons have zero issues pulling the correct names / servers from LFG.

**Comment by CreepyJoker** [comment]
Greetings,

I was a bit stuck with work and I forgot about it, sorry.
I've provided a fix for it, should be available with the next data update.

Let me know if there are any other issues.

I will have to rewrite some stuff as Blizz has finally decided to unify and standardize some UI objects. Meanwhile, the provided fix should do the trick.


Best regards.
