### ISSUE TITLE
just hide tooltip if no data is found

### ISSUE THREAD

**Issue by grand-lotus-iroh** [antrix1/arenamaster-addon#2]
I want to love the addon but there is hardly any data for anyone.

How do I hide the bloat in the tooltip if there is no data found? So, only display data if arena profile found... IF NOT, just hide tooltip entry?

**Comment by antrix1** [comment]
Hey and thanks for the feedback. There is currently no way to hide the empty tooltips, but we'll hide the empty ones by default in one of the upcoming versions.

The current database consists of around 170k characters for EU & US. Have in mind it's the beginning of the expansion and a lot of people are playing new characters that were never searched on the website. 

The website database is updated daily with the leaderboard data, which includes top 5000 players for each bracket in each region. Now that the PvP Season started, a lot of new characters will be added and existing ones will be updated.

As for the addon data update, the plan is to update the addon data weekly, at least until the user base grows enough to setup daily updates. I'll probably do a mass update of all existing characters in the upcoming week and after that, the only way to update a character for the following week would be if they appear in the leaderboard or are searched for manually, either directly on the website or through a profile link from the game. 

So for the time being, when encountering characters & tooltips with no data, feel free to open their ArenaMaster profile and add them to the website, and that data will be available to everyone on the next addon update.

As soon as more people start using the addon and the website, the data will be more frequently updated and more relevant to everyone so please go ahead and share the website and addon with anyone you think would find it useful.

Cheers,
Antrix
