### ISSUE TITLE
Weird Tooltip like window appears only when arenamaster addon is enabled.

### ISSUE THREAD

**Issue by shfthappens** [antrix1/arenamaster-addon#20]
So when I have arena master addon enabled a weird blank tooltip like window appears in my social window. Disabling the addon removes it. Tried to delete the saved variables etc. and reinstall the addon from scratch but it still shows up.

Attached screenshot 

![WoWScrnShot_112122_102539](https://user-images.githubusercontent.com/83546856/202949396-3f06933a-2c34-4f39-a339-a200d5117585.jpg)

I get this error when first logging in

Message: Interface/AddOns/ArenaMasterPvPInspect/ui/ui.lua:320: GameTooltip doesn't have a "OnTooltipSetUnit" script
Time: Mon Nov 21 10:49:52 2022
Count: 1
Stack: Interface/AddOns/ArenaMasterPvPInspect/ui/ui.lua:320: GameTooltip doesn't have a "OnTooltipSetUnit" script
[string "=[C]"]: in function `HookScript'
[string "@Interface/AddOns/ArenaMasterPvPInspect/ui/ui.lua"]:320: in main chunk

Locals: (*temporary) = GameTooltip {
 0 = <userdata>
 SetQuestLogRewardSpell = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestPartyProgress = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessLineData = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:303
 SetPvpTalent = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetRuneforgeResultItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetHyperlink = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnit = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetAzeriteEssence = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetVoidDepositItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetVoidWithdrawalItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetInfoBackdropStyle = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:338
 shoppingTooltips = <table> {
 }
 SetSocketGem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 updateTooltipTimer = 0.200000
 ItemTooltip = Frame {
 }
 StatusBar = GameTooltipStatusBar {
 }
 SetLootCurrency = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetSlottedKeystone = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetWorldCursor = <function> defined @Interface/FrameXML/GameTooltip.lua:952
 SetLootItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetMerchantCostItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 GetUnit = <function> defined @Interface/FrameXML/GameTooltip.lua:994
 SetOwnedItemByID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetItemInteractionItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestLogSpecialItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 TextRight1 = GameTooltipTextRight1 {
 }
 SetEnhancedConduit = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetRecipeReagentItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestCurrency = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 supportsDataRefresh = true
 SetWeeklyReward = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetMerchantItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetPvpBrawl = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetAchievementByID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 BottomOverlay = Texture {
 }
 SetSpellByID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 supportsItemComparison = true
 SetSocketedRelic = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessInfo = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:236
 ProcessLines = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:293
 NineSlice = Frame {
 }
 SetInventoryItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 RefreshData = <function> defined @Interface/FrameXML/GameTooltip.lua:933
 SetTransmogrifyItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444

**Comment by nonstopjoker** [comment]
Go to AddOns/ArenaMasterPvPInspect/ui/ui.lua and open with a text editor, press ctrl+F and find `GameTooltip:HookScript("OnTooltipSetUnit", function(self, ...)` 
and replace it with: 
`TooltipDataProcessor.AddTooltipPostCall(Enum.TooltipDataType.Unit,function(GameTooltip, data)`

save file and reload or restart game, it should work.

**Comment by shfthappens** [comment]
Awesome. That fixed it. Thank you!

**Comment by CreepyJoker** [comment]
Greetings, thanks for your report.

The issue was now fixed and it should come live with the next release ( later on today ), so you can update the AddOn freely.
I'll keep an eye on it if other issues get by ( I'll have to check some other API changes and push another update if that's needed ).

Have a great one!
