### ISSUE TITLE
Addon

### ISSUE THREAD

**Issue by tucuxia** [antrix1/arenamaster-addon#21]
The addon options can't be opened anymore with Dragonflight, and with the weird box over my raid panel I had to turn it off completely. If there is not a new way to open options, then something is broken because /ampvp doesn't work anymore.

**Comment by tucuxia** [comment]
Also the website has detached my main from my account completely, and nothing is working to add it back. I checked that the addon is running on my main and it seems to be, but it took hours to get her to reimport correctly and I still can't attach her to my account.

**Comment by antrix1** [comment]
@tucuxia Thanks for letting me know. I'll take a look today and message you on Discord for a follow-up after debugging.
