### ISSUE TITLE
Addon shows correct rating for Highest All-Time 3s, but not RBGs on either of my characters.

### ISSUE THREAD

**Issue by gudvibesz** [antrix1/arenamaster-addon#3]
Title says it all.  I have 2 characters that achieved over 2300 RBG rating, but they only show my current season highest rating - whereas my highest 3s rating is correctly displayed as 2825.  I earned both my highest arena and RBG ratings in the same season, so I am not sure why the RBG rating does not load.

**Comment by antrix1** [comment]
@gudvibesz Does the website show the correct highest rbg experience? Can you give me a link to one of your character's profiles, so I can compare if the website & addon data are in sync or if something else is the case?
