### ISSUE TITLE
bug everytime i tooltip someone

### ISSUE THREAD

**Issue by ardCOR3** [antrix1/arenamaster-addon#6]
Message: ...e\AddOns\ArenaMasterPvPInspect\modules/framework.lua:369: attempt to compare number with nil
Time: Wed Apr 14 13:46:17 2021
Count: 17
Stack: ...e\AddOns\ArenaMasterPvPInspect\modules/framework.lua:369: attempt to compare number with nil
[string "@Interface\AddOns\PersoLootRoll\Core\Addon.lua"]:591: in function `origErrorHandler'
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:758: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=[C]"]: ?
[string "@Interface\AddOns\ArenaMasterPvPInspect\modules/framework.lua"]:369: in function `AMPVP_RatingColorManager'
[string "@Interface\AddOns\ArenaMasterPvPInspect\core.lua"]:190: in function `AMPVP_AddTooltipDetails'
[string "@Interface\AddOns\ArenaMasterPvPInspect\ui/ui.lua"]:318: in function <Interface\AddOns\ArenaMasterPvPInspect\ui/ui.lua:297>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetUnit'
[string "@Interface\FrameXML\UnitFrame.lua"]:462: in function `UnitFrame_UpdateTooltip'
[string "@Interface\FrameXML\UnitFrame.lua"]:452: in function <Interface\FrameXML\UnitFrame.lua:451>
[string "=[C]"]: ?
[string "@Interface\FrameXML\SecureHandlers.lua"]:266: in function <Interface\FrameXML\SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@Interface\FrameXML\SecureHandlers.lua"]:322: in function <Interface\FrameXML\SecureHandlers.lua:306>
[string "=(tail call)"]: ?

Locals: msg = "...e\AddOns\ArenaMasterPvPInspect\modules/framework.lua:369: attempt to compare number with nil"
lvl = nil
origHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355
self = <table> {
 Unit = <table> {
 }
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface\AddOns\Ace3\AceTimer-3.0\AceTimer-3.0.lua:147
 Help = <function> defined @Interface\AddOns\PersoLootRoll\Core\Addon.lua:292
 ABBR = "PLR"
 UnregisterComm = <function> defined @Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 CHAT_MSG_WHISPER = <function> defined @Interface\AddOns\PersoLootRoll\Core\Events.lua:324
 TimerIsRunning = <function> defined @Interface\AddOns\PersoLootRoll\Core\Addon.lua:674
 lastLocked = <table> {
 }
 EVENT_VOTE = <function> defined @Interface\AddOns\PersoLootRoll\Core\Events.lua:683
 errorPrev = 8001.564000
 OnActiveChanged = <function> defined @Interface\AddOns\PersoLootRoll\Core\Addon.lua:368
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:409
 state = 3
 EVENT_ROLL_STATUS = <function> defined @Interface\AddOns\PersoLootRoll\Core\Events.lua:644
 CHANNEL_ALPHA = "alpha"
 IsEnabled = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:451
 ScheduleTimer = <function> defined @Interface\AddOns\Ace3\AceTimer-3.0\AceTimer-3.0.lua:94
 IsTracking = <function> defined @Interface\AddOns\PersoLootRoll\Core\Addon.lua:362
 versionNoticeShown = false
 errors = 0
 RegisterMessage = <function> defined @Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 ECHO_LEVELS = <table> {
 }
 EVENT_BID = <function> defined @Interface\AddOns\PersoLootRoll\Core\Events.lua:657
 hooks = <table> {
 }
 CheckState = <function> defined @Interface\AddOns\PersoLootRoll\Core\Addon.lua:307
 SendCommMessage = <function> defined @Interface\AddOns\Ace3\AceComm-3.0\AceComm-3.0.lua:87
 RegisterErrorHandler = <function> defined @Interface\AddOns\PersoLootRoll\Core\Addon.lua:583
 EnableChatLinksHook = <function> defined @Interface\AddOns\PersoLootRoll\Core\Hooks.lua:272
 LogExport = <function> defined @Interface\AddOns\PersoLootRoll\Core\Addon.lua:562
 UnregisterAllComm = <function> defined @Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 SetEnabledState = <function> defined @Interface\AddOns\Ace3\AceAddon

**Comment by CreepyJoker** [comment]
The issue got solved now, it will be available with the next update release.

Thanks for your report!

**Comment by ardCOR3** [comment]
thank you
