### ISSUE TITLE
Add an option to hide it while in combat or in BG / Arena

### ISSUE THREAD

**Issue by danielsawan** [antrix1/arenamaster-addon#7]
Tbh it is very cool to have all those stats in game but while in combat it just horrible to target the tooltip take all the screen and hide big portion of the screen.

**Comment by CreepyJoker** [comment]
Hello, thank you for your feedback.

I will add two new options that should arrive with the next build and these will be present in the "Settings UI -> Remove tooltip when" section: 
- In combat;
- In arenas / battlegrounds ( will be disabled entirely, ignoring your Arenas/Battlegrounds settings if enabled );

Keep in mind that these will not be enabled by default, therefore selecting specific settings that apply to your needs / likings must be configured.

You also have the options to specifically enable/disable specific sections in arenas/battlegrounds by simply typing '/ampvp' and clicking the "Arenas/Battlegrounds Settings".

**Comment by CreepyJoker** [comment]
Done, added the new options in the latest commit. 
These should come in effect with the next release.

Thank you once again for your feedback.

**Comment by danielsawan** [comment]
wow that was so quick thanks :D
